replicaCount: 1

image:
  registry: ghcr.io
  repository: mlflow/mlflow
  tag: 2.14.3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

mlflow:
  backend: "sqlite:///mlflow.db"
  defaultArtifactRoot: "/mlruns"

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 50Mi
  storageClass: gp2
