# values.yaml for ArgoCD deployment of Bitnami MLflow

replicaCount: 1

image:
  registry: docker.io
  repository: bitnami/mlflow
  tag: 3.3.2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80  # expose MLflow on port 80 internally

ingress:
  enabled: false  # set true if you want ArgoCD to manage ingress
  annotations: {}
  hosts:
    - host: mlflow.example.com
      paths:
        - /
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

# PostgreSQL backend
postgresql:
  enabled: true
  postgresqlDatabase: mlflow
  postgresqlUsername: mlflow_user
  postgresqlPassword: mlflow_password
  persistence:
    enabled: true
    size: 1Gi

# MinIO for artifact storage
minio:
  enabled: true
  accessKey: minio
  secretKey: minio123
  persistence:
    enabled: true
    size: 5Gi
  service:
    type: ClusterIP
    port: 9000

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 5Gi

# MLflow configuration
mlflow:
  backendStore: postgresql
  artifactStore: s3
  s3:
    bucket: mlflow
    endpoint: my-mlflow-minio:9000
    secure: false

# Optional: RBAC for MLflow UI
rbac:
  create: true

# Optional: Logging configuration
logging:
  level: info
