replicaCount: 1

image:
  registry: docker.io
  repository: bitnami/mlflow
  tag: 3.3.2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

mlflow:
  backend: "sqlite:///bitnami/mlflow/mlflow.db"
  defaultArtifactRoot: "/bitnami/mlflow/artifacts"

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 2Gi
  storageClass: gp2

