replicaCount: 1

image:
  registry: docker.io
  repository: bitnami/mlflow
  tag: 3.3.2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: false
  hostname: mlflow.example.com
  annotations: {}
  tls: []

persistence:
  enabled: true
  storageClass: standard   # EBS CSI StorageClass
  accessModes:
    - ReadWriteOnce
  size: 10Gi

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

env:
  BACKEND_STORE_URI: sqlite:///mlflow.db
  ARTIFACT_ROOT: /bitnami/mlflow/artifacts

nodeSelector: {}
tolerations: []
affinity: {}

metrics:
  enabled: false
