replicaCount: 1

image:
  registry: docker.io
  repository: bitnami/mlflow
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

tracking:
  tls:
    enabled: false
  metrics:
    enabled: false
    
postgresql:
  enabled: true
  postgresqlDatabase: mlflow
  postgresqlUsername: mlflow_user
  postgresqlPassword: mlflow_password
  persistence:
    enabled: true
    storageClass: "" # use default StorageClass

minio:
  enabled: true
  accessKey: minio
  secretKey: minio123
  persistence:
    enabled: true
    storageClass: "" # use default StorageClass
  service:
    type: ClusterIP
    port: 9000

mlflow:
  backendStore: postgresql
  artifactStore: s3
  s3:
    bucket: mlflow
    endpoint: my-mlflow-minio:9000
    secure: false

rbac:
  create: true
logging:
  level: info
