replicaCount: 1

image:
  registry: docker.io
  repository: bitnami/mlflow
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

# PostgreSQL backend
postgresql:
  enabled: true
  postgresqlDatabase: mlflow
  postgresqlUsername: mlflow_user
  postgresqlPassword: mlflow_password
  persistence:
    enabled: true
    storageClass: ""  # use default StorageClass
    accessMode: ReadWriteOnce

# MinIO for artifact storage
minio:
  enabled: true
  accessKey: minio
  secretKey: minio123
  persistence:
    enabled: true
    storageClass: ""  # use default StorageClass
    accessMode: ReadWriteOnce
  service:
    type: ClusterIP
    port: 9000

# MLflow configuration
mlflow:
  backendStore: postgresql
  artifactStore: s3
  s3:
    bucket: mlflow
    endpoint: my-mlflow-minio:9000
    secure: false

# Optional: RBAC for MLflow UI
rbac:
  create: true

# Optional: Logging configuration
logging:
  level: info
