apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mlflow.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mlflow.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mlflow.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: mlflow
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: MLFLOW_BACKEND_STORE_URI
              value: "{{ .Values.mlflow.backend }}"
            - name: MLFLOW_DEFAULT_ARTIFACT_ROOT
              value: "{{ .Values.mlflow.defaultArtifactRoot }}"
          volumeMounts:
            - name: mlflow-data
              mountPath: "{{ .Values.mlflow.defaultArtifactRoot }}"
      volumes:
        - name: mlflow-data
          persistentVolumeClaim:
            claimName: {{ include "mlflow.fullname" . }}
