apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mlflow.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "mlflow.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
